CHAIN:
  MODEL: "gpt-3.5-turbo"
  CHAIN_TYPE: "stuff"
  DEFAULT_VECTORSTORE: "FAISS"
  TIKTOKEN_ENCODING_NAME: "cl100k_base"

UI:
  PAGE_TITLE: "maum PDF-GPT"
  PAGE_ICON: "random"
  PAGE_LAYOUT: "wide"
  DEFAULT_SLIDER_STEPS: 10
  DEFAULT_CHUNK_SIZE: 680
  DEFAULT_CHUNK_OVERLAP: 150
  MAX_TOKENS: 4097

Elasticsearch: