CHAIN:
  MODEL: "gpt-3.5-turbo"
  CHAIN_TYPE: "stuff"
  DEFAULT_VECTORSTORE: "FAISS"
  TIKTOKEN_ENCODING_NAME: "cl100k_base"
  EMBEDDING: "OpenAI"

EMBEDDING:
  OPEN_AI: "text-embedding-ada-002"
  SENTENCE_TRANSFORMER: "all-mpnet-base-v2"
  ELASTIC_SEARCH: ""

UI:
  PAGE_TITLE: "maum PDF-GPT"
  PAGE_ICON: "random"
  PAGE_LAYOUT: "wide"
  DEFAULT_SLIDER_STEPS: 10
  DEFAULT_CHUNK_SIZE: 680
  DEFAULT_CHUNK_OVERLAP: 150
  MAX_TOKENS: 4097

Elasticsearch: